In [1]:
import numpy as np
import sklearn as skl
import csv
import nltk
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
X_train = np.concatenate((np.array(pd.read_csv("./paul_train_features.csv").values)[:,1:3], 
                         np.array(pd.read_csv("./paul_train_graph.csv"))),
                         axis=1)
y_train = np.array(pd.read_csv("./paul_my_train.csv"))[:,2]

tmp = []
for i in range(len(X_train)):
    if X_train[i,2]==-1:
        tmp.append([X_train[i,0], X_train[i,1], 20, X_train[i,3]])
    else:
        tmp.append([X_train[i,0], X_train[i,1], X_train[i,2], X_train[i,3]])

X_train = np.array(tmp)

X_test  = np.concatenate((np.array(pd.read_csv("./paul_test_features.csv").values)[:,1:3], 
                         np.array(pd.read_csv("./paul_test_graph.csv"))),
                         axis=1)
y_test = np.array(pd.read_csv("./paul_my_test.csv"))[:,2]

tmp = []
for i in range(len(X_test)):
    if X_test[i,2]==-1:
        tmp.append([X_test[i,0], X_test[i,1], 20, X_test[i,3]])
    else:
        tmp.append([X_test[i,0], X_test[i,1], X_test[i,2], X_test[i,3]])

X_test = np.array(tmp)

In [3]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(492409, 4) (492409,) (123103, 4) (123103,)


In [4]:
sample_size = 80000

from sklearn.ensemble import AdaBoostClassifier
csf = AdaBoostClassifier(learning_rate=1)
csf.fit(X_train[:sample_size], y_train[:sample_size])
csf.score(X_test, y_test)

/Users/paulracaniere/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


0.955289473042899

In [ ]:
sample_size = 100000

from sklearn.ensemble import RandomForestClassifier
csf = RandomForestClassifier()
csf.fit(X_train[:sample_size], y_train[:sample_size])
csf.score(X_test, y_test)

In [ ]:
sample_size = 10000

from sklearn.gaussian_process import GaussianProcessClassifier
csf = GaussianProcessClassifier()
csf.fit(X_train[:sample_size], y_train[:sample_size])
csf.score(X_test, y_test)

In [16]:
result = csf.predict_proba(np.concatenate((np.array(pd.read_csv("./paul_kaggle_features.csv").values)[:,1:3],
                            np.array(pd.read_csv("./paul_kaggle_graph.csv"))),
                            axis=1))
print(result)

[[0.50402551 0.49597449]
 [0.46857107 0.53142893]
 [0.46287442 0.53712558]
 ...
 [0.50990656 0.49009344]
 [0.51402666 0.48597334]
 [0.50990656 0.49009344]]


In [17]:
result = result[:,1]
print(result)

[0.49597449 0.53142893 0.53712558 ... 0.49009344 0.48597334 0.49009344]


In [18]:
result = (result >= np.sort(result)[len(result)//2])*1
print(result)
print(sum(result),len(result))

[0 1 1 ... 0 0 0]
16334 32648


In [19]:
with open("./paul_prediction.csv","w") as f:
    writer = csv.writer(f)
    writer.writerow(["ID", "category"])
    for i,a in enumerate(result):
        writer.writerow([i,a])